language: python
python:
- '3.4'
- '3.5'
- '3.6'
install: ./regenerate_parsers.sh
script:
- python -m unittest test.py
deploy:
  on:
    branch: master
    python: '3.6'
  skip_cleanup: true
  provider: pypi
  user: TMiguelT
  distributions: sdist bdist_wheel
  password:
    secure: TLQfV3ZBvHIFb7leJrI/E3O9vxaDcFsYfSVSzlhJFl9PwwjLCWUOtDDoXKiwPQFxhPdqoGgULknUxXay06ooqi2kKe1uATHb0SR0WQ6bglc9qrLjjSJhrgWme4shNCw5yTz3MomJOqFSjVHIPJCFMgzLG/hzxa0LNRQQeCfK3gRDadPRblgpUhyeZY0xUAexxl+tZuGS1x1Yd78aypfbw2J1+bo/dwrcf7mdr0qZuB9jm/6FEreHAiwqhN03+zzCTXoHC/IL/2tVsBfwDm9hWDER8/BLRphg9+XU2GSYUoyqx6x4MhXJmrUHFs52c2lOdlyGvarh0oXusKsXbAVC+6r7uaM1Cxvnm9TqwOX6iiDm8UGzg2CgECcahfwNq0CWiLuJdfsT7DjG3Q0FedfaWY4X127IspETy21tmoY0rKrJ2S88QGel2hYkSmP37+WchQRmbdg5+BfpvQrjOz3uR/RUuPUn1K0kddX0+z92RdO2kcL2HZoNffVo41QA7haRGKUz75gOWYgUdt7aHcYH5EVc5x8DleoQ3/wJetbMDaWBu884XdsxqzqQAQiGPm2qewzIXYNA0sah0iImMJb7gHf2esbeNPDi9vTCiyrLhpbXvFw0H2yQhiprRinDLU5qz+syTElmWnRXQWjDYy85VrQBGPjQNoVdwZEi4cOieH4=
