language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- |
  for version_path in wdl/versions/*; do
    version=`basename $version_path`
    grammar=$version_path/parsers/grammar.hgr

    if [[ -f $grammar ]]; then
      hermes generate $version_path/parsers/grammar.hgr --language=python --name=$version --header --directory wdl_parser
    fi
  done

  rename 's/-/_/g' wdl_parser/*
  rename 's/_parser.py/.py/g' wdl_parser/*
script:
- python -m unittest test.py
deploy:
  on:
    branch: master
    python: '3.6'
  skip_cleanup: true
  provider: pypi
  user: TMiguelT
  distributions: sdist bdist_wheel
  password:
    secure: FqZ/tnQKUjnYmihCH6T0bTXigS8lM1ZU/wljGDJlBLXD+Xw6fVvxF7HazMgQ9qENI1Qod64cbJEhJrG+4HGEG0jQAh9QlsGcCRe18tcCLQjfg1rdPvjta4/bUvrvVzAl4clfBdhyheQPohOeJJcu5bgFOHi2iS3JgHzTYvjkDWTNsquGVjpM8QEyYPeKq3jfjFuXAKXXgKdc6EzDWgfyzma/DunwUpL4ny4pTRLJd6EZK7/s/bv9OI9h7v25C9k9a5zQIz6EYOKrtPZ+uEqan7KzNR3JV0ARZPSSLYBvfnXe7l1MgUlJLDbPwYNieCI4QLSi97/92yMKW++EhcTxMljl2ut555xeqi8rIUALGLy0kg27MoVUur0cH9ylF6o0+RkAjTXH3C5Hc/va7TFpqGw5cT7ZsAllxOLRMTQGj73MEA3XOuozvgDijkzelF2b8t5D9nNKRUtHPn80JxLhMMYghmdtp4CgKmuZP8Fb2Drlzrq1ec3+bhtJxLCJDCc9VQn5T5qGwbg+v8nIBzBID9Hx3VYne0TbApCDgcA8DnJ2f6IHKiD5rP327YGhi36bwlA3RMh5vO1UKLGa62Z+jLj+JJVCELPZ6ucIVuDrUK/Rc21WcAvq1HxxksTlhkT1nyvXb6WMyHhEyC+KcH9qhvtqyKmTl8QdizEW2Q6rEe8=
