language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- |
  for version_path in wdl/versions/*; do
    version=`basename $version_path`
    grammar=$version_path/parsers/grammar.hgr

    if [[ -f $grammar ]]; then
      hermes generate $version_path/parsers/grammar.hgr --language=python --name=$version --header --directory wdl_parser
    fi
  done

  rename 's/-/_/g' wdl_parser/*
  rename 's/_parser.py/.py/g' wdl_parser/*
script:
- python -m unittest test.py
deploy:
  on:
    branch: master
    python: '3.6'
  skip_cleanup: true
  provider: pypi
  user: TMiguelT
  distributions: sdist bdist_wheel
  password:
    secure: j/Cx0UrfJ/ZCW8v7WPoAnuW6KHceASXB20gOA5Ex1Nke61UU0zwMuRCY+i+gN0WVZarNqFOWrnI9xGzhmTrHw8pNynJ7knZ4fsgPavcz55EYtqqbRNPSbKf65WlWysswYjReaU7q6Gh8KvTKnGjQlXm+Af78lb/amDgWEZ4CwritahFMiDezEAerzym4qIvvifuzK5qnSFoIVaU4Zd/6IcfnIRHXZzqvqzWGKLrVId5BLb9pkrREVbcsobYQDCfd7fpb8EW1c4SIpFP4yAHuK3YLRwlhoY6DWxHhFAqh6WQHWe53TLaBDUVU9lculSmVfsfHJYAYoyHD1ULtt3TeDP9WWM0NUj2YXzhKFJUn/1KS9W/9bGhmhkq+i7hbHlKQhqy+AHmfQ74QHurKaEKUC2FKJgvStlcNlsy6NVuI4DitJO8dAaFLmp2cYMJJy6coLKPKNJOM11QPWEgEFN3wPGBD5aOUH+yjBOAzPQ6OGu+zg30LpLgXByzcgK5Iys+31BDt4Z8aeZ00amak5KznLLro2lZaLE8kwwhitUMkX/RuVNnpZfNE0PGaGRLq0pmZPUByiO5NHKdLN9hZzZXlwqc0Xk4yGOOmHtzhr9O/23trvQI7qjsKSo/A3w17BGy8fZlNwUKR00ABRDmw8a4HHfGnbo20CVAMfgz/HtskfnA=
